name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: pip install tox
      - run: tox
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    env:
      PYPI_USERNAME: ${{ secrets.$PYPI_USERNAME }}
      PYPI_PASSWORD: ${{ secrets.$PYPI_PASSWORD }}
      PYPI_TEST_USERNAME: ${{ secrets.$PYPI_TEST_USERNAME }}
      PYPI_TEST_PASSWORD: ${{ secrets.$PYPI_TEST_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: pip install twine
      - run: python setup.py sdist bdist_wheel
      - run: twine upload -u $PYPI_TEST_USERNAME -p $PYPI_TEST_PASSWORD --repository-url https://test.pypi.org/legacy/ dist/*
      - run: twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*
